disable most CI for iteration

diff --git a/.github/workflows/integration-tests.yaml b/.github/workflows/integration-tests.yaml
--- a/.github/workflows/integration-tests.yaml
+++ b/.github/workflows/integration-tests.yaml
@@ -16,268 +16,268 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  integration-tests-mac:
-    name: "macOS: Integration tests"
-    runs-on: [macOS, self-hosted, ARM64]
-    env:
-      GRADLE_OPTS: -Dorg.gradle.daemon=false
-      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
-      GITHUB_USER: cricut-builduser
-      CONFIGURATION: debug
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  # integration-tests-mac:
+  #   name: "macOS: Integration tests"
+  #   runs-on: [macOS, self-hosted, ARM64]
+  #   env:
+  #     GRADLE_OPTS: -Dorg.gradle.daemon=false
+  #     GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
+  #     GITHUB_USER: cricut-builduser
+  #     CONFIGURATION: debug
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Setup git credentials
-        uses: de-vri-es/setup-git-credentials@v2
-        with:
-          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/
+  #     - name: Setup git credentials
+  #       uses: de-vri-es/setup-git-credentials@v2
+  #       with:
+  #         credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/
 
-      - name: Setup JDK
-        uses: actions/setup-java@v3
-        with:
-          distribution: zulu
-          java-version: 20
+  #     - name: Setup JDK
+  #       uses: actions/setup-java@v3
+  #       with:
+  #         distribution: zulu
+  #         java-version: 20
 
-      - name: Setup node
-        uses: actions/setup-node@v3
-        with:
-          node-version: '18.x'
-          registry-url: 'https://npm.pkg.github.com/'
-          scope: '@cricut'
+  #     - name: Setup node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: '18.x'
+  #         registry-url: 'https://npm.pkg.github.com/'
+  #         scope: '@cricut'
 
-      - name: Setup dotnet
-        uses: actions/setup-dotnet@v4
-        with:
-          dotnet-version: '6'
+  #     - name: Setup dotnet
+  #       uses: actions/setup-dotnet@v4
+  #       with:
+  #         dotnet-version: '6'
 
-      - name: Install generation tools
-        shell: zsh {0}
-        run: |
-          yq --version || brew install yq
+  #     - name: Install generation tools
+  #       shell: zsh {0}
+  #       run: |
+  #         yq --version || brew install yq
 
-      - name: Force clear nuget cache
-        run: "dotnet nuget locals all --clear"
+  #     - name: Force clear nuget cache
+  #       run: "dotnet nuget locals all --clear"
 
-      - uses: dart-lang/setup-dart@v1
+  #     - uses: dart-lang/setup-dart@v1
 
-      - name: Ensure re-generating does not change committed generated code
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Ensure re-generating does not change committed generated code
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          cd integration-tests/TestAPI
+  #         cd integration-tests/TestAPI
 
-          FISHYJOES=1 swift run -- fishy-joes generate
+  #         FISHYJOES=1 swift run -- fishy-joes generate
 
-          if [ ! -z "$(cd integration-tests/TestAPI; git status --porcelain .)" ]; then
-            echo '::error:: generation modified sources'
-            echo '::error::   run `FISHYJOES=1 swift run fishy-joes generate` from integration-tests/TestAPI and re-commit'
-            git diff
-            git status
-            exit 1
-          fi
+  #         if [ ! -z "$(cd integration-tests/TestAPI; git status --porcelain .)" ]; then
+  #           echo '::error:: generation modified sources'
+  #           echo '::error::   run `FISHYJOES=1 swift run fishy-joes generate` from integration-tests/TestAPI and re-commit'
+  #           git diff
+  #           git status
+  #           exit 1
+  #         fi
 
-      - name: Build FishyJoesNodeRuntime
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Build FishyJoesNodeRuntime
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          ./scripts/compile-node-runtime.sh
+  #         ./scripts/compile-node-runtime.sh
 
-      - name: Test TypeScript from npm via fishy-joes
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Test TypeScript from npm via fishy-joes
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          cd integration-tests/TestAPI
-          FISHYJOES=1 swift run -- fishy-joes --nodejs build test
+  #         cd integration-tests/TestAPI
+  #         FISHYJOES=1 swift run -- fishy-joes --nodejs build test
 
-      - name: Build FishyJoesIotaRuntime
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Build FishyJoesIotaRuntime
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          ./scripts/compile-iota-runtime.sh
+  #         ./scripts/compile-iota-runtime.sh
 
-      - name: Test C♯ from dotnet via fishy-joes
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Test C♯ from dotnet via fishy-joes
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          cd integration-tests/TestAPI
-          FISHYJOES=1 swift run -- fishy-joes --c-sharp build test
+  #         cd integration-tests/TestAPI
+  #         FISHYJOES=1 swift run -- fishy-joes --c-sharp build test
 
-      - name: Test Dart from dart via fishy-joes
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Test Dart from dart via fishy-joes
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          cd integration-tests/TestAPI
-          FISHYJOES=1 swift run -- fishy-joes --dart build test
+  #         cd integration-tests/TestAPI
+  #         FISHYJOES=1 swift run -- fishy-joes --dart build test
 
-      - name: Build FishyJoesJavaRuntime
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Build FishyJoesJavaRuntime
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          libdir=kotlin-runtime/src/generated/resources/mac
-          rm -rf $libdir
-          mkdir -p $libdir
-          ./scripts/compile-kotlin-native-runtime.sh
-          (cd kotlin-runtime && ./gradlew publishToMavenLocal)
+  #         libdir=kotlin-runtime/src/generated/resources/mac
+  #         rm -rf $libdir
+  #         mkdir -p $libdir
+  #         ./scripts/compile-kotlin-native-runtime.sh
+  #         (cd kotlin-runtime && ./gradlew publishToMavenLocal)
 
-      - name: Test kotlin from gradle via fishy-joes
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Test kotlin from gradle via fishy-joes
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          cd integration-tests/TestAPI
-          FISHYJOES=1 swift run -- fishy-joes --kotlin-fast build test
+  #         cd integration-tests/TestAPI
+  #         FISHYJOES=1 swift run -- fishy-joes --kotlin-fast build test
 
-  integration-tests-ubuntu:
-    name: "Ubuntu: Integration tests"
-    env:
-      GRADLE_OPTS: -Dorg.gradle.daemon=false
-      GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
-      GITHUB_USER: cricut-builduser
-      CONFIGURATION: debug
+  # integration-tests-ubuntu:
+  #   name: "Ubuntu: Integration tests"
+  #   env:
+  #     GRADLE_OPTS: -Dorg.gradle.daemon=false
+  #     GITHUB_TOKEN: ${{ secrets.CRICUT_GPR_TOKEN }}
+  #     GITHUB_USER: cricut-builduser
+  #     CONFIGURATION: debug
 
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
 
-      - name: Setup git credentials
-        uses: de-vri-es/setup-git-credentials@v2
-        with:
-          credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/
+  #     - name: Setup git credentials
+  #       uses: de-vri-es/setup-git-credentials@v2
+  #       with:
+  #         credentials: https://cricut-builduser:${{ secrets.CRICUT_GPR_TOKEN }}@github.com/
 
-      - name: Login to github registry
-        uses: docker/login-action@v2
-        with:
-          username: cricut-builduser
-          password:  ${{ secrets.CRICUT_GPR_TOKEN }}
-          registry: ghcr.io
+  #     - name: Login to github registry
+  #       uses: docker/login-action@v2
+  #       with:
+  #         username: cricut-builduser
+  #         password:  ${{ secrets.CRICUT_GPR_TOKEN }}
+  #         registry: ghcr.io
 
-      - name: Setup JDK
-        uses: actions/setup-java@v3
-        with:
-          distribution: zulu
-          java-version: 20
+  #     - name: Setup JDK
+  #       uses: actions/setup-java@v3
+  #       with:
+  #         distribution: zulu
+  #         java-version: 20
 
-      - name: Setup node
-        uses: actions/setup-node@v3
-        with:
-          node-version: '18.x'
-          registry-url: 'https://npm.pkg.github.com/'
-          scope: '@cricut'
+  #     - name: Setup node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: '18.x'
+  #         registry-url: 'https://npm.pkg.github.com/'
+  #         scope: '@cricut'
 
-      - name: Setup dotnet
-        uses: actions/setup-dotnet@v4
-        with:
-          dotnet-version: '6'
+  #     - name: Setup dotnet
+  #       uses: actions/setup-dotnet@v4
+  #       with:
+  #         dotnet-version: '6'
 
-      - uses: dart-lang/setup-dart@v1
+  #     - uses: dart-lang/setup-dart@v1
 
-      - name: Configure build environment
-        run: |
-          set -euxo pipefail
+  #     - name: Configure build environment
+  #       run: |
+  #         set -euxo pipefail
 
-          sudo apt-get install zsh
+  #         sudo apt-get install zsh
 
-          # Sadly, Ubuntu LTS doesn't have an up-to-date binaryen, so use a wasm version instead
-          npm -g install binaryen@111.0.0
+  #         # Sadly, Ubuntu LTS doesn't have an up-to-date binaryen, so use a wasm version instead
+  #         npm -g install binaryen@111.0.0
 
-          SWIFT_WASM_VERSION="5.10-SNAPSHOT-2024-04-26-a"
-          curl -Lo swift-wasm.tgz "https://github.com/swiftwasm/swift/releases/download/swift-wasm-$SWIFT_WASM_VERSION/swift-wasm-$SWIFT_WASM_VERSION-ubuntu20.04_x86_64.tar.gz"
-          sudo mkdir -p "/Library/Developer/Toolchains/swift-wasm-$SWIFT_WASM_VERSION.xctoolchain"
-          sudo tar -xf swift-wasm.tgz -C "/Library/Developer/Toolchains/swift-wasm-$SWIFT_WASM_VERSION.xctoolchain" --strip-components 1
+  #         SWIFT_WASM_VERSION="5.10-SNAPSHOT-2024-04-26-a"
+  #         curl -Lo swift-wasm.tgz "https://github.com/swiftwasm/swift/releases/download/swift-wasm-$SWIFT_WASM_VERSION/swift-wasm-$SWIFT_WASM_VERSION-ubuntu20.04_x86_64.tar.gz"
+  #         sudo mkdir -p "/Library/Developer/Toolchains/swift-wasm-$SWIFT_WASM_VERSION.xctoolchain"
+  #         sudo tar -xf swift-wasm.tgz -C "/Library/Developer/Toolchains/swift-wasm-$SWIFT_WASM_VERSION.xctoolchain" --strip-components 1
 
-      - name: Build FishyJoesNodeRuntime
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Build FishyJoesNodeRuntime
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          ./scripts/compile-node-runtime.sh
+  #         ./scripts/compile-node-runtime.sh
 
-      - name: Test TypeScript from npm via FishyJoes
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Test TypeScript from npm via FishyJoes
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          cd integration-tests/TestAPI
-          FISHYJOES=1 swift run -- fishy-joes --nodejs --wasm build test
+  #         cd integration-tests/TestAPI
+  #         FISHYJOES=1 swift run -- fishy-joes --nodejs --wasm build test
 
-      - name: Build FishyJoesIotaRuntime
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Build FishyJoesIotaRuntime
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          ./scripts/compile-iota-runtime.sh
+  #         ./scripts/compile-iota-runtime.sh
 
-      - name: Test C♯ from dotnet via fishy-joes
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Test C♯ from dotnet via fishy-joes
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          cd integration-tests/TestAPI
-          FISHYJOES=1 swift run -- fishy-joes --c-sharp build test
+  #         cd integration-tests/TestAPI
+  #         FISHYJOES=1 swift run -- fishy-joes --c-sharp build test
 
-      - name: Test Dart from dart via fishy-joes
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Test Dart from dart via fishy-joes
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          cd integration-tests/TestAPI
-          FISHYJOES=1 swift run -- fishy-joes --dart build test
+  #         cd integration-tests/TestAPI
+  #         FISHYJOES=1 swift run -- fishy-joes --dart build test
 
-      - name: Build linux FishyJoesJavaRuntime
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Build linux FishyJoesJavaRuntime
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          libdir=kotlin-runtime/src/generated/resources/linux
-          rm -rf $libdir
-          mkdir -p $libdir
-          ./scripts/compile-kotlin-native-runtime.sh
+  #         libdir=kotlin-runtime/src/generated/resources/linux
+  #         rm -rf $libdir
+  #         mkdir -p $libdir
+  #         ./scripts/compile-kotlin-native-runtime.sh
 
-      # Running this step messes with permissions significantly,
-      # in particular causing subsequent git checkouts to fail, so testing of Kotlin / Java is being done last
-      - name: Build android FishyJoesJavaRuntime
-        uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185
-        with:
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-          registry: ghcr.io
-          image: ghcr.io/cricut/android-swift-runtime:3.0.1
-          options: -v ${{ github.workspace }}:/work -w /work
-          run: /work/scripts/compile-android-runtime.sh
+  #     # Running this step messes with permissions significantly,
+  #     # in particular causing subsequent git checkouts to fail, so testing of Kotlin / Java is being done last
+  #     - name: Build android FishyJoesJavaRuntime
+  #       uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185
+  #       with:
+  #         username: ${{ github.actor }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
+  #         registry: ghcr.io
+  #         image: ghcr.io/cricut/android-swift-runtime:3.0.1
+  #         options: -v ${{ github.workspace }}:/work -w /work
+  #         run: /work/scripts/compile-android-runtime.sh
 
-      - name: Locally publish kotlin native & android runtimes
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Locally publish kotlin native & android runtimes
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          # Publish runtime for the native linux test and the android tests
-          (cd kotlin-runtime && ./gradlew publishToMavenLocal)
+  #         # Publish runtime for the native linux test and the android tests
+  #         (cd kotlin-runtime && ./gradlew publishToMavenLocal)
 
-      - name: Test kotlin from gradle via fishy-joes
-        shell: zsh {0}
-        run: |
-          set -euxo pipefail
+  #     - name: Test kotlin from gradle via fishy-joes
+  #       shell: zsh {0}
+  #       run: |
+  #         set -euxo pipefail
 
-          cd integration-tests/TestAPI
-          FISHYJOES=1 swift run -- fishy-joes --kotlin build test
+  #         cd integration-tests/TestAPI
+  #         FISHYJOES=1 swift run -- fishy-joes --kotlin build test
 
-          # Publish test-api for the android tests to use later
-          (cd bindings/kotlin/generated && ./gradlew publishToMavenLocal)
+  #         # Publish test-api for the android tests to use later
+  #         (cd bindings/kotlin/generated && ./gradlew publishToMavenLocal)
 
-      - name: Upload artifacts for use by Android later
-        uses: actions/upload-artifact@v4
-        with:
-          name: maven-local
-          path: ~/.m2/repository
+  #     - name: Upload artifacts for use by Android later
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: maven-local
+  #         path: ~/.m2/repository
 
   integration-tests-windows:
     name: "Windows: Integration tests"
